<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<h1 class="text-center">Books list</h1>
<hr>

<div class="container-fluid text-center">
    <div class="row">
        <?php foreach ($books as $book) : ?>
            <div class="col-md-3 my-1 mx-5" style="border: 1px solid blue;">
                <img src="/webroot/img/fon_1.jpg" style="width: 200px; height: 250px;">
                <div class="caption">
                    <h3><?=$book['title']?></h3>
                    <p class="m-0">author: <?=$book['author']?></p>
                    <p>
                        <a href="/registration/book-<?=$book['id']?>.html" class="btn btn-success" role="button">Details</a>
                    </p>
                </div>

            </div>

        <?php endforeach; ?>
    </div>
</div>

</body>
</html>