<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<h1 class="text-center">Books list</h1>
<nav aria-label="Page navigation example" style="padding-left: 370px">
    <ul class="pagination my-5">
        <?php foreach ($pagination->buttons as $button) :
            if ($button->isActive) : ?>
                <li class="page-item"><a class="page-link text-success" href="?page=<?=$button->page?>"><?=$button->text?></a></li>

            <?php else : ?>
                <li class="page-item disabled"><a class="page-link" style="background-color: #28a745; color: #fff;" href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>
    </ul>
</nav>
<hr>

<div class="container-fluid text-center">
    <div class="row">
        <?php foreach ($books as $book) : ?>
            <div class="col-md-3 my-1 mx-5" style="border: 1px solid #28a745;">
                <img src="/webroot/img/fon_1.jpg" style="width: 200px; height: 250px;">
                <div class="caption">
                    <h3><?=$book['title']?></h3>
                    <p class="m-0">author: <?=$book['author']?></p>
                    <p>
                        <a href="/registration/book-<?=$book['id']?>.html" class="btn btn-success" role="button">Details</a>
                    </p>
                </div>

            </div>

        <?php endforeach; ?>
    </div>
</div>
<nav aria-label="Page navigation example" style="padding-left: 370px">
    <ul class="pagination my-5">
        <?php foreach ($pagination->buttons as $button) :
            if ($button->isActive) : ?>
                <li class="page-item"><a class="page-link text-success" href="?page=<?=$button->page?>"><?=$button->text?></a></li>

            <?php else : ?>
                <li class="page-item disabled"><a class="page-link" style="background-color: #28a745; color: #fff;" href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>
    </ul>
</nav>

</body>
</html>