<h1 class="text-center my-4">Results found:</h1>

<div class="container-fluid text-center">
    <div class="row">
        <?php foreach ($reply as $item) : ?>
            <div class="col-md-2 my-1 mx-5" style="border: 1px solid #28a745;">
                <img src="/webroot/img/fon_1.jpg" style="width: 170px; height: 200px;">
                <div class="caption">
                    <h5><?=$item['title']?></h5>
                    <p class="m-0">genre: <?=$item['genre']?></p>
                    <p class="m-0">author: <?=$item['author']?></p>
                    <p>
                        <a href="/registration/book-<?=$item['id']?>.html" class="btn btn-success" role="button">Details</a>
                    </p>
                </div>

            </div>

        <?php endforeach; ?>
    </div>
</div>