<h1 class="text-center"><?=$book['title']?></h1>
<hr>

<div class="text-center mb-5" style="border: 1px solid blue; width: 800px; margin-left: 280px;">
    <img class="my-2" src="/webroot/img/fon_1.jpg" width="400px" height="600px">


    <h3><?=$book['title']?></h3>
    <p><?=$book['description']?></p>
    <p><b>author: <?=$book['author']?></b></p>
    <p><b>genre: <?=$book['genre']?></b></p>
    <a href="/registration/favorites/<?=$book['id']?>" class="btn btn-primary mb-5" role="button">Add to favorites</a>
    <a href="/webroot/books/<?=$book['book_contents']?>.pdf" class="btn btn-outline-primary mb-5" role="button" download>Download</a>
</div>
