<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin add</title>
</head>
<body>
<div class="container-fluid fon">
    <h1 class="text-center">The form of adding a book</h1>
    <div class="alert text-center h2 text-primary"><b><?=\Library\Session::getFlash()?></b></div>

    <form method="post">
        <div class="form-group">
            <input type="text" placeholder="Book title" class="form-control text-danger" id="title" name="title">
        </div>
        <div class="form-group">
            <input type="text" placeholder="Book author" class="form-control text-danger" id="author" name="author">
        </div>
        <div class="form-group">
            <input type="text" placeholder="Book genre" class="form-control text-danger" id="genre" name="genre">
        </div>
        <div class="form-group">
            <input type="text" placeholder="Book contents" class="form-control text-danger" id="genre" name="book_contents">
        </div>
        <div class="form-group">
            <textarea class="form-control text-danger" placeholder="Book description" id="description" rows="3" name="description"></textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-outline-danger px-5">Submit</button>
        </div>
    </form>
    <form method="post" enctype="multipart/form-data" class="text-center">
        <div class="alert text-center h2 text-primary"><b><?=\Library\Session::getFlash()?></b></div>
        <input type="file" class="form-control mb-3" name="file" id="file">
        <input type="submit" class="btn btn-danger mb-5" value="Upload"/>
    </form>
</div>

</body>
</html>