<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin add</title>
</head>
<body>
<div class="container-fluid fon">
    <h1 class="text-center">The form of adding a book</h1>
    <div class="alert text-center h2 text-primary"><b><?=\Library\Session::getFlash()?></b></div>

    <form method="post">
        <div class="form-group">
            <label for="exampleFormControlInput1">Book title</label>
            <input type="text" class="form-control text-danger" id="title" name="title">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Book author</label>
            <input type="text" class="form-control text-danger" id="author" name="author">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Book genre</label>
            <input type="text" class="form-control text-danger" id="genre" name="genre">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Book description</label>
            <textarea class="form-control text-danger" id="description" rows="3" name="description"></textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-danger px-5">Submit</button>
        </div>
    </form>
</div>

</body>
</html>