<div class="table-responsive">
    <script>
        function deleteArticle(){
            alert('The book was successfully deleted!');
        }
    </script>
    <table class="table table-striped table-danger m-0" >
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>Action</th>
        </tr>

        <?php foreach ($books as $book) : ?>
            <tr>
                <td><?=$book['id']?></td>
                <td><?=$book['title']?></td>
                <td><?=$book['author']?></td>
                <td><?=$book['genre']?></td>
                <td>
                    <a href="/admin/books/edit/<?=$book['id']?>" class="text-danger">Edit</a>
                    <a href="/admin/add" class="text-danger">Add</a>
                    <a href="/admin/books/remove/<?=$book['id']?>" onclick="deleteArticle(this)" class="text-danger">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>
</div>