<table border="1" width="100%" cellspacing="0" cellpadding="10">
    <tr>
        <th>№</th>
        <th>Title</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($books as $book) : ?>
    <tr>
        <td>
            <?=$book->getId();?>
        </td>
        <td>
            <?=$book->getTitle();?>
        </td>
        <td>
            <?=$book->getPrice();?>
        </td>
        <td>
            <a href="/admin/books/<?=$book->getId()?>">Edit</a> <br>
            <a href="#">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>