<h1 class="text-center">Login</h1>

<div class="alert small text-danger text-center"><b class="h1"><?=\Library\Session::getFlash()?></b></div>

<form method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email" value="<?=$form->email ?>">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="password" name="password">
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary px-5">Submit</button>
    </div>
</form>