<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC admin</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="1000px">
            <ul class="navbar-nav my-2">
                <li class="nav-item active ml-5">
                    <a href="/admin" class="text-white">Admin</a>
                </li>
                <li class="nav-item active mx-4">
                    <a href="/admin/books" class="text-white">Books</a>
                </li>
                <li class="nav-item">
                    <a href="/logout" class="text-white">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

<?=$content?>

</body>
</html>