<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC admin</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<body>
<div class="container-fluid m-0 p-0" style="padding-top: 100px;">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #170629;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="1000px">
            <ul class="navbar-nav my-2">
                <li class="nav-item active ml-5">
                    <a href="/admin">Admin</a>
                </li>
                <li class="nav-item active mx-4">
                    <a href="/admin/books">Books</a>
                </li>
                <li class="nav-item">
                    <a href="/logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<?=$content?>

</body>
</html>