<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MVC</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="/" class="nav-link text-white">Главная</a>
            </li>
            <li class="nav-item">
                <a href="/books" class="nav-link text-white">Книги</a>
            </li>
            <li class="nav-item">
                <a href="/contact-us" class="nav-link text-white">Регистрация</a>
            </li>
            <li class="nav-item">
                <a href="/login" class="nav-link text-white">Вход</a>
            </li>
        </ul>
    </div>
</nav>
<b><?=\Library\Session::getFlash()?></b>

<?=$content?>

</body>
</html>