<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MVC registration</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-success sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="/registration" class="nav-link text-white">Home</a>
            </li>
            <li class="nav-item">
                <a href="/registration/books" class="nav-link text-white">Books</a>
            </li>
            <li class="nav-item">
                <a href="/registration/favorites" class="nav-link text-white">Favorites</a>
            </li>
            <li class="nav-item">
                <a href="/logout" class="nav-link text-white">Logout</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="post" action="/registration/search">
            <input type="text" class="form-control mr-sm-2" placeholder="Search" aria-label="Search" name="query">
            <button type="submit" class="btn btn-outline-warning my-2 my-sm-0">Поиск</button>
        </form>
    </div>
</nav>
<b><?=\Library\Session::getFlash()?></b>

<?=$content?>

</body>
</html>